"""update rental payment fields

Revision ID: 0aa726984625
Revises: 8a1234567890
Create Date: 2026-08-24 16:12:23.301672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa726984625'
down_revision: Union[str, Sequence[str], None] = '8a1234567890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Update rental_items.rental_id foreign key
    op.drop_constraint(
        op.f("rental_items_rental_id_fkey"),
        "rental_items",
        type_="foreignkey",
    )

    op.create_foreign_key(
        "rental_items_rental_id_fkey",
        "rental_items",
        "rentals",
        ["rental_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Remove security deposit from rental items
    op.drop_column(
        "rental_items",
        "security_deposit",
    )

    # Add initial payment
    op.add_column(
        "rentals",
        sa.Column(
            "initial_payment",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.00"),
        ),
    )

    # Add remaining amount
    op.add_column(
        "rentals",
        sa.Column(
            "remaining_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            server_default=sa.text("0.00"),
        ),
    )

    # Existing rentals:
    # remaining_amount = total_amount - initial_payment
    op.execute(
        """
        UPDATE rentals
        SET remaining_amount = total_amount - initial_payment
        """
    )

    # Remove security deposit from rentals
    op.drop_column(
        "rentals",
        "security_deposit",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('security_deposit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('rentals', 'remaining_amount')
    op.drop_column('rentals', 'initial_payment')
    op.add_column('rental_items', sa.Column('security_deposit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rental_items', type_='foreignkey')
    op.create_foreign_key(op.f('rental_items_rental_id_fkey'), 'rental_items', 'rentals', ['rental_id'], ['id'])
    # ### end Alembic commands ###
