"""add customer tenant phone unique constraint

Revision ID: 7441a2b197ae
Revises: d615ce9ed3c1
Create Date: 2026-08-16 10:21:28.068707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7441a2b197ae'
down_revision: Union[str, Sequence[str], None] = 'd615ce9ed3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
