class ErrorCodes:

    USER_NOT_FOUND = "USER_NOT_FOUND"

    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"

    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"

    UNAUTHORIZED = "UNAUTHORIZED"

    FORBIDDEN = "FORBIDDEN"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"